name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        working-directory: application
        run: npm install

      - name: Lint
        working-directory: application
        run: npm run lint

      - name: Type-check
        working-directory: application
        run: npx tsc --noEmit

      - name: Build Next.js app
        working-directory: application
        run: npm run build
